CREATE DATABASE CAMPEONATOCPS;
USE CAMPEONATOCPS;

CREATE TABLE IF NOT EXISTS CITY  (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    STATE CHAR(2) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS SPORT (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
    Gender CHAR(1) NOT NULL,
    IsInvidual TINYINT(1) NOT NULL,
    TeamSize TINYINT NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ETEC (
	Number SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL,
    
    CityId SMALLINT UNSIGNED NOT NULL,
    
    PRIMARY KEY(Number)
);

ALTER TABLE ETEC ADD CONSTRAINT FK_ETEC_CITY
 FOREIGN KEY (CityId) REFERENCES CITY(ID);
 
 CREATE TABLE IF NOT EXISTS TEAM (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    CreatedDate DATETIME NOT NULL,
    
    EtecNumber SMALLINT UNSIGNED NOT NULL,
    SportId TINYINT UNSIGNED NOT NULL,
    
    PRIMARY KEY(ID)
 );
 
ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_ETEC
	FOREIGN KEY(EtecNumber) REFERENCES ETEC(Number);
    
ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_SPORT
	FOREIGN KEY (SportId) REFERENCES SPORT(ID);
    
CREATE TABLE IF NOT EXISTS STUDENT (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(60) NOT NULL,
    BirthDate DATE NOT NULL,
    Gender CHAR(1) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    
    TeamId SMALLINT UNSIGNED NOT NULL,
    
    PRIMARY KEY(ID)
);

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_TEAM
	FOREIGN KEY (TeamId) REFERENCES TEAM(ID);
    
CREATE TABLE IF NOT EXISTS GAME (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    GameDate DATETIME NOT NULL,
    Team1Points SMALLINT NOT NULL,
    Team2Points SMALLINT NOT NULL,
    
    SportId TINYINT UNSIGNED NOT NULL,
    Team1Id SMALLINT UNSIGNED NOT NULL,
    Team2Id SMALLINT UNSIGNED NOT NULL,
    
    PRIMARY KEY (ID)
);

ALTER TABLE GAME ADD CONSTRAINT FK_GAME_SPORT
	FOREIGN KEY (SportId) REFERENCES SPORT(ID);
    
ALTER TABLE GAME ADD CONSTRAINT FK_GAME_TEAM1
	FOREIGN KEY (Team1Id) REFERENCES TEAM(ID);
    
ALTER TABLE GAME ADD CONSTRAINT FK_GAME_TEAM2
	FOREIGN KEY (Team2Id) REFERENCES TEAM(ID);
